name: CheckIp

# on:
#   schedule:
#     - cron: '* 6 * * *'

on: [push]


jobs:
  checkIP:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false 
          fetch-depth: 0 

      - name: Set up nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: install
        run: npm install
      
      - name: run to check
        run: npm run start
      # - name: Commit
      #   run: |
      #    git config --global user.name github-actions
      #    git config --global user.email github-actions[bot]@users.noreply.github.com
      #    git add .
      #    git commit -m"action:`date`"
      
      # - name: Commit && Push changes
      #   uses: actions-js/push@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: 'master'
      #     message: 'bot-action'
      - name: Commit
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          npm version patch -m "[RELEASE] %s"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - uses: fastify/github-action-merge-dependabot@v2.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
