name: CheckIp

# on:
#   schedule:
#     - cron: '* 6 * * *'

on: [push]


jobs:
  checkIP:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false 

      - name: Set up nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: install
        run: npm install
      
      - name: run to check
        run: npm run start
      - name: Commit
        run: |
         git config --global user.name "Mrwang6w"
         git config --global user.email "1134481134@qq.com"
         git add .
         git commit -m "action:`date`" 
         git pull
         git push origin
      
      - name: Push
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          branch: ${{ github.head_ref }}


