on: 
  repository_dispatch:
    types:
      - webhook-run


jobs:
  checkIP:

    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v3
        with:
          persist-credentials: false 
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: printInputs
        run: |
         echo "Log level: ${{ github.event.client_payload.logLevel }}"

      - name: Set up nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: install
        run: npm install
      
      - name: run to check
        run: npm run test 
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          message:  Auto update  at ${{date}}
          add: "*"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}